# Generated by Django 3.2.21 on 2023-10-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfb_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pubDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
