# Generated by Django 3.2.21 on 2023-10-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qfb_main', '0002_comment_newsarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_content',
        ),
    ]
