# Generated by Django 3.2.21 on 2023-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfb_main', '0003_auto_20231006_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
