# Generated by Django 3.2.21 on 2023-10-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfb_main', '0004_newsarticle_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
