# Generated by Django 3.2.21 on 2023-10-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qfb_main', '0004_alter_comment_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='NewsArticle',
            new_name='news_article',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='pubDate',
            new_name='pub_date',
        ),
    ]
