# Generated by Django 3.2.21 on 2023-10-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfb_main', '0005_auto_20231006_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
