# Generated by Django 3.2.21 on 2023-10-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfb_main', '0006_alter_newsarticle_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='language',
            field=models.CharField(max_length=255),
        ),
    ]
